baseURL = "/"
languageCode = "en-gb"
title = "Alizarin Viewer"
publishDir = "docs"
canonifyurls = true

[build.buildStats]
  enable = true

[build.buildStats.esbuild]
  external = ["fs", "path", "url", "crypto", "stream", "util", "events", "buffer", "os", "node:fs", "node:path", "node:url"]

[markup.goldmark.renderer]
unsafe = true

[params]
govuk = false
logotext = "ABC"
product = "Alizarin Viewer"
phase = "alpha"
feedbackurl = "/feedback/"
cookies = "/cookies/"

[[module.mounts]]
source = "content"
target = "content"

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "data"
target = "data"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "layouts"
target = "layouts"

[module]
  [[module.imports]]
    path = 'github.com/flaxandteal/hugo-cookies'
