baseURL = "/"
languageCode = "en-gb"
title = "Starches"
theme = "govukhugo"
publishDir = "docs"
canonifyurls = true

[markup.goldmark.renderer]
unsafe = true

[params]
govuk = false
logotext = "ABC"
product = "Starches Quickview"
phase = "alpha"
feedbackurl = "/feedback/"
archesurl = "http://localhost:8000/"

[[module.mounts]]
source = "content"
target = "content"
