baseURL = "/"
languageCode = "en-gb"
title = "Alizarin Viewer"
publishDir = "docs"
canonifyurls = true

[markup.goldmark.renderer]
unsafe = true

[params]
govuk = false
logotext = "ABC"
product = "Alizarin Viewer"
phase = "alpha"
feedbackurl = "/feedback/"
cookies = "/cookies/"

[[module.mounts]]
source = "content"
target = "content"

[module]
  [[module.imports]]
    path = 'github.com/flaxandteal/hugo-cookies'
  [[module.imports]]
    path = 'github.com/flaxandteal/govukhugo'
