baseURL = "/"
languageCode = "en-gb"
title = "Alizarin Viewer"
theme = "govukhugo"
publishDir = "docs"
canonifyurls = true

[markup.goldmark.renderer]
unsafe = true

[params]
govuk = false
logotext = "ABC"
product = "Alizarin Viewer"
phase = "alpha"
feedbackurl = "/feedback/"
cookies = "/cookies/"

[[module.mounts]]
source = "content"
target = "content"
